-- ============================================================================
-- Memoring backend schema — run once in Supabase → SQL Editor → New query → Run
-- ============================================================================

create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  install_id  uuid not null,
  name        text not null,
  props       jsonb default '{}'::jsonb,
  app_version text,
  platform    text,
  created_at  timestamptz not null default now()
);
create index if not exists events_created_idx on public.events(created_at);
create index if not exists events_name_idx    on public.events(name);
create index if not exists events_install_idx on public.events(install_id);

create table if not exists public.feedback (
  id          bigint generated by default as identity primary key,
  install_id  uuid,
  message     text not null,
  rating      int,
  contact     text,
  app_version text,
  created_at  timestamptz not null default now()
);

create table if not exists public.announcements (
  id          bigint generated by default as identity primary key,
  title       text,
  body        text not null,
  action_url  text,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Row Level Security: the app's public key can ONLY do these three things.
alter table public.events        enable row level security;
alter table public.feedback      enable row level security;
alter table public.announcements enable row level security;

drop policy if exists events_insert        on public.events;
drop policy if exists feedback_insert      on public.feedback;
drop policy if exists announcements_read   on public.announcements;

create policy events_insert      on public.events        for insert to anon with check (true);
create policy feedback_insert    on public.feedback      for insert to anon with check (true);
create policy announcements_read on public.announcements for select to anon using (active = true);
